// app/metadata.ts
import { Metadata } from "next";

// This file exports metadata separately from the layout
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
